#!/bin/bash
# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a shout
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Install dependencies
sudo apt-get install nodejs-legacy npm -y -qq

# Copy files to the right place
final_path=/var/www/shout
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Set permissions to shout directory
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/shout.conf

# Reload nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
