#!/bin/bash
# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a shout
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Install dependencies
sudo apt-get install nodejs-legacy npm -y -qq
sudo npm install forever -g

# Copy files to the right place
final_path=/var/www/shout
sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

# Install app dependencies
cd $final_path
sudo npm cache clear
sudo npm install
cd -

# Set permissions to shout directory
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/shout.conf

# Copy init.d script
sudo cp ../conf/shout /etc/init.d/
sudo chmod +x /etc/init.d/shout
sudo update-rc.d shout defaults

# Public chat
if [ "$is_public" = "Yes" ];
then
sudo yunohost app setting shout unprotected_uris -v "/"
fi

# Reload nginx and regenerate SSOwat conf
sudo service shout start
sudo service nginx reload
sudo yunohost app ssowatconf
